### ISSUE TITLE
Add API tests to CI + coverage

### ISSUE THREAD

**Issue by doradsoft** [bible-on-site/bible-on-site#482]
- [ ] Need to open two processes on web/api, one calls `cargo make test-coverage` and the second `cargo make test-e2e`. see how I did it for linting
the coverage will be automatically generated into web/api/.coverage. then we can merge with website coverage.
merging is a bit tricky:
- [ ] if api coverage was reported and website wasn't then need to grab the previous coverage report from artifacts then merge, same the opposite. Only if both are reported then it's an immediate merge.
The artifact path for api is `web/api/.coverage/e2e.lcov`
The artifact path for website is `web/bible-on-site/coverage/merged/lcov.info`
- [ ] To merge them run `npm run coverage:merge` in working dir: `scripts`
- [ ] modify coverage reporting tools to use the newly merged coverage report file
```yml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.WEBSITE_DIRECTORY }}/coverage/merged/lcov.info
          disable_search: true

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{ env.WEBSITE_DIRECTORY }}/coverage/merged/lcov.info
```
to
```
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .coverage/lcov.info
          disable_search: true

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: .coverage/lcov.info
```
- [ ] Modify readme in a manner that coverage badge is for * modules and not just for website.
- [ ] Bonus: set a badge for each module separately
